import Head from "next/head";
import { FC, ReactNode } from "react";

type Props = {
  children?: ReactNode;
};

export const SeoProvider: FC<Props> = ({ children }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>{children}</main>

    <footer></footer>
  </>
);
